### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by HexM7** [Dragonizedpizza/djs-slash-commands#2]
I don't get where I'm doing it wrong.
My command file:
```javascript
const Discord = require("discord.js");
module.exports = {
    name: 'avatar',
    description: 'Gets a user\'s avatar',
    commandOptions: [{
        name: "USER",
        description: "Optional user mention or Snowflake ID",
        type: "6"
    }],
    global: false,
   ```
   
   My main file:

   ```javascript
    const commandFiles = fs.readdirSync('./slashCommands/').filter(file => file.endsWith('.js'));
  for (const file of commandFiles) {
      const command = require(`./slashCommands/${file}`);
      if (command && command.global !== true) {
         client.SlashCommands.add({
          name: command.name,
          description: command.description,
          options: command.commandOptions
        }, "GUILD_ID");
    };
      if (command && command.global !== true) {
        client.SlashCommands.add({
          name: command.name,
          description: command.description,
          options: command.commandOptions
        });
      };
      
```
  
  Console output:
  ```
TypeError: Cannot read property 'name' of undefined
    at \node_modules\djs-slash-commands\index.js:17:42
    at Array.map (<anonymous>)
    at SlashCommandHandler.add (\node_modules\djs-slash-commands\index.js:15:27)
    at initSlash (\index.js:67:31)
    at Client.<anonymous> (\index.js:84:9)
    at Client.emit (events.js:327:22)
   
```

**Comment by Dragonizedpizza** [comment]
@HexM7 could you try upgrading your djs-slash-commands version?

**Comment by HexM7** [comment]
The package is up to date.

**Comment by Dragonizedpizza** [comment]
>   at \node_modules\djs-slash-commands\index.js:17:42
![image](https://user-images.githubusercontent.com/70718540/124910621-173bc100-dfec-11eb-911f-0daf62fee77a.png)
I just updated everything, index.js has only 11 lines.

**Comment by HexM7** [comment]
Nevermind, I fixed it by pusing commands to an array and then using the `bulkAdd` command. Thank you anyways

**Comment by Dragonizedpizza** [comment]
:+1:

**Comment by Dragonizedpizza** [comment]
I'd suggest upgrading though, 
![image](https://user-images.githubusercontent.com/70718540/124911091-ab0d8d00-dfec-11eb-9c4d-d4efa46f40ea.png)
the new update allows you to reply, edit reply, delete reply, and also allows you to actually *see* the command object

**Comment by HexM7** [comment]
I'll definitely upgrade the package, it helps keep the code pretty, short & neat :D
